variables:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true
  System.Debug: true

steps:

- task: NodeTool@0
  inputs:
    versionSpec: "8.9.1"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.3.2"

- script: |
    git config --global core.autocrlf false
    git config --global core.safescrlf true
    git reset --hard

- powershell: |
    yarn
    .\node_modules\.bin\gulp electron
    .\node_modules\.bin\tsc -p .\src\tsconfig.monaco.json --noEmit
    npm run compile
  name: build

- powershell: |
    node --version
    .\scripts\test.bat
    .\scripts\test-integration.bat
  name: test

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\NPM\Cache\_logs'
    ArtifactName: 'npm_logs'
    ArtifactType: 'Container'
  condition: always()
